INSERT INTO movel(descricao,marca,categoria,"anoAquisicao",localizacao) VALUES
('Sofá de couro', 'Tok&Stok', 'Movel', 2021, 'Sala'),
('Mesa de jantar', 'Etna', 'Movel', 2020, 'Sala'),
('Cama de casal', 'Ortobom', 'Movel', 2019, 'Quarto'),
('Guarda-roupa', 'MadeiraMadeira', 'Movel', 2018, 'Quarto'),
('Geladeira', 'Brastemp', 'Eletrodomestico', 2017, 'Cozinha'),
('Fogão', 'Electrolux', 'Equipamento', 2016, 'Cozinha'),
('Poltrona', 'Mobly', 'Movel', 2021, 'Sala'),
('Rack', 'Casas Bahia', 'Movel', 2020, 'Sala'),
('TV', 'Samsung', 'Eletrodomestico', 2019, 'Sala'),
('Ar-condicionado', 'LG', 'Eletrodomestico', 2018, 'Quarto'),
('Ventilador', 'Arno', 'Eletrodomestico', 2017, 'Quarto'),
('Micro-ondas', 'Panasonic', 'Eletrodomestico', 2016, 'Cozinha'),
('Liquidificador', 'Philips', 'Eletrodomestico', 2015, 'Cozinha'),
('Cadeira', 'Tramontina', 'Movel', 2021, 'Sala'),
('Banco', 'Oppa', 'Movel', 2020, 'Sala'),
('Colchão', 'Castor', 'Movel', 2019, 'Quarto'),
('Cômoda', 'Móveis Província', 'Movel', 2018, 'Quarto'),
('Forno', 'Fischer', 'Equipamento', 2017, 'Cozinha'),
('Torradeira', 'Oster', 'Eletrodomestico', 2016, 'Cozinha'),
('Cortina', 'Corttex', 'Texil', 2015, 'Sala');

