INSERT INTO movel(descricao,marca,categoria,"anoAquisicao",localizacao) VALUES
('Sofá de couro', 'Tok&Stok', 'Sala de estar', 2021, 'Sala'),
('Mesa de jantar', 'Etna', 'Sala de jantar', 2020, 'Sala'),
('Cama de casal', 'Ortobom', 'Quarto', 2019, 'Quarto'),
('Guarda-roupa', 'MadeiraMadeira', 'Quarto', 2018, 'Quarto'),
('Geladeira', 'Brastemp', 'Cozinha', 2017, 'Cozinha'),
('Fogão', 'Electrolux', 'Cozinha', 2016, 'Cozinha'),
('Poltrona', 'Mobly', 'Sala de estar', 2021, 'Sala'),
('Rack', 'Casas Bahia', 'Sala de estar', 2020, 'Sala'),
('TV', 'Samsung', 'Sala de estar', 2019, 'Sala'),
('Ar-condicionado', 'LG', 'Quarto', 2018, 'Quarto'),
('Ventilador', 'Arno', 'Quarto', 2017, 'Quarto'),
('Micro-ondas', 'Panasonic', 'Cozinha', 2016, 'Cozinha'),
('Liquidificador', 'Philips', 'Cozinha', 2015, 'Cozinha'),
('Cadeira', 'Tramontina', '', 2021, 'Sala'),
('Banco', 'Oppa', '', 2020, 'Sala'),
('Colchão', 'Castor', '', 2019, 'Quarto'),
('Cômoda', 'Móveis Província', '', 2018, 'Quarto'),
('Forno', 'Fischer', '', 2017, 'Cozinha'),
('Torradeira', 'Oster', '', 2016, 'Cozinha'),
('Cortina', 'Corttex', '', 2015, 'Sala');

